added in upsert product view... getting an error
Severity Code Description Project File Line Suppression State
Error CS1503 Argument 2: cannot convert from 'System.Collections.Generic.IEnumerable<System.Web.Mvc.SelectListItem>' to 'System.Collections.Generic.IEnumerable<Microsoft.AspNetCore.Mvc.Rendering.SelectListItem>' EricsBookStore C:\Users\W0774957\source\repos\EricsBookStore\EricsBookStore\Areas\Admin\Views\Product\Upsert.cshtml 70 Active